/* rk-study · client/dict.js —— 词典
 *
 * 由入口 client.js 用原生 import() 加载的 ES 模块(loader 的 chunk 协议只认插件根目录的
 * client.<名>.js, 装不下子目录)。依赖由入口注入, 本文件不碰 window.__ModuleLoader__。
 */
export function createDict(deps) {
	const zh = {
		panel: '知识点笔记',
		title: '卡片知识点 · 学习画布',
		subtitle: '目录 = 大章节 · 文件 = 小节 · 知识点 + 题目',
		search: '搜索知识点、小节、标签…',
		all: '全部',
		note: '笔记',
		question: '题目',
		refresh: '重新扫描',
		chapters: '章节',
		sections: '小节',
		points: '知识点',
		examples: '题目',
		words: '字',
		empty: '还没有笔记。点右上角「新建章节」，或先把 markdown 放进工作区。',
		emptyChapter: '这一章还没有小节',
		noMatch: '没有匹配的内容',
		back: '返回',
		backToMap: '章节图',
		close: '关闭',
		edit: '编辑',
		openSection: '打开',
		editSection: '编辑小节',
		editPoint: '编辑知识点',
		editQuestionFile: '编辑题目',
		renameChapter: '编辑章节名称',
		rename: '改名',
		newSection: '新建小节',
		newPoint: '新建知识点',
		addQuestion: '＋ 添加题目',
		noQuestionYet: '这个知识点还没有题目，点右侧按钮添加。',
		questionFile: '题目文件',
		insertQuestion: '插入题目模板',
		ownFile: '独立文件',
		newChapter: '新建章节',
		save: '保存',
		saving: '保存中…',
		saved: '已保存',
		cancel: '取消',
		close: '关闭',
		title2: '标题',
		kind: '类型',
		parent: '上级目录',
		create: '创建',
		reveal: '答案已遮挡 · 点击展开',
		revealAll: '显示全部答案',
		hideAll: '隐藏全部答案',
		collapse: '收起答案',
		emptyBody: '（本节暂无文字说明）',
		emptyPoints: '这个小节还没有识别到知识点：用「## 知识点 N：标题」分段即可。',
		loading: '载入中…',
		zoomIn: '放大',
		zoomOut: '缩小',
		fit: '复位',
		fontLabel: '字号',
		fontSmaller: '缩小字号',
		fontLarger: '放大字号',
		fontHint: '字号：点一下恢复 100%',
		skinLabel: '配色',
		skinHint: '配色与主题（参考 Material Design 色板）',
		themeLabel: '主题',
		themeDark: '深色',
		themeLight: '浅色',
		themeAuto: '跟随系统',
		themeHint: '跟随系统：跟 macOS 的外观设置（浅色 / 深色）自动切，系统一变立刻就换',
		cardColors: '卡片各用一色',
		cardColorsHint: '让每个章节 / 小节 / 知识点带自己的颜色，一屏里不会全是同一个色',
		cardColorsOn: '开',
		cardColorsOff: '关',
		skinTech: '科技蓝（默认）',
		skinBlue: 'Material 蓝',
		skinCyan: 'Material 青',
		skinTeal: 'Material 蓝绿',
		skinGreen: 'Material 绿',
		skinLime: 'Material 柠檬',
		skinAmber: 'Material 琥珀',
		skinOrange: 'Material 橙',
		skinDeepOrange: 'Material 深橙',
		skinRed: 'Material 红',
		skinPink: 'Material 粉',
		skinPurple: 'Material 紫',
		skinDeepPurple: 'Material 深紫',
		skinIndigo: 'Material 靛蓝',
		skinBlueGrey: 'Material 蓝灰',
		focus: '全屏',
		focusHint: '藏掉左侧边栏，画布占满整个窗口（再点一下恢复，Esc 也行）',
		focusExit: '退出全屏',
		questions: '题目',
		subPoints: '子知识点',
		subTopics: '小知识点',
		searchHits: '匹配的知识点',
		chars: '字符',
		modeCanvas: '画布',
		modeMap: '思维导图',
		rootTitle: '我的学习画布',
		rootSubtitle: '一个画布 = 一个笔记根目录，放什么笔记都行',
		rootCount: '个画布',
		rootNew: '新建学习画布',
		rootNewHint: '选一个磁盘目录当这个画布的根目录（不填就按名字建在导入的学习库里），里面会自动建 notes/ 和 questions/（模板统一放在学习库根目录的 .templates/）',
		rootEnter: '进入画布',
		rootDefault: '内置',
		rootForget: '移出列表',
		rootForgetHint: '把它移到同层的 .remove/ 里备份，再从列表移除',
		rootRemoved: '已移出列表（目录移到同层的 .remove/ 里了）',
		rootCreated: '画布建好了',
		rootScanning: '正在统计…',
		rootNeedPath: '请填一个绝对路径，例如 /Users/you/Desktop/我的笔记',
		rootName: '画布名字',
		rootPathLabel: '根目录',
		rootPathHint: '绝对路径；不填就按名字建在导入的学习库里（还没导入过就建议放桌面）。目录不存在会自动创建，里面会放 notes/ 和 questions/（模板统一放在学习库根目录的 .templates/）',
		rootCreate: '创建',
		rootRename: '改画布名字',
		rootRenameHint: '改名会直接重命名磁盘上的目录（目录名就是画布名）；同一层里不能有同名画布',
		rootNameTaken: '已经有同名的画布了，换个名字',
		rootNeedName: '名字不能为空',
		rootRenamed: '目录已改名',
		rootAll: '全部画布',
		rootAllHint: '回到全部学习画布',
		rootHint: '一级画布：点卡片进入某个画布；＋ 新建一个学习画布；⇪ 导入目录 可直接导入一个已有的笔记库',
		rootHintUnder: '新画布默认建在',
		rootRescanned: '已重新扫描',
		rootGone: '已移出 {n} 个磁盘上已经不存在的画布',
		settings: '设置',
		settingsHint: '设置：画布存放目录',
		defaultRoot: '画布存放目录',
		defaultRootHint: '新建的每个学习画布都建在它下面的一个子目录里（例：/Users/你/Desktop/WorkNotes/数据结构）。把它设到插件目录以外，插件的笔记就和插件本身分开了。',
		currentCanvas: '当前画布',
		settingsAll: '一级画布（还没进入任何画布）',
		settingsPluginDefault: '插件配置（cordis.patch.yml）里的默认根目录',
		dirNotes: '笔记目录',
		dirQuestions: '题目目录',
		dirTemplates: '模板目录',
		settingsSaveOnly: '只保存',
		settingsSaveEnter: '保存并新建画布',
		settingsSaved: '设置已保存',
		settingsNeedAbs: '请填一个绝对路径，例如 /Users/你/Desktop/学习笔记',
		libImport: '导入目录',
		libTitle: '导入已有目录',
		libLabel: '目录',
		libNoPicker: '这个环境没有目录选择器，请手动填绝对路径。',
		libPicking: '选择中…',
		libChoose: '📁 选择…',
		libHint: '选一个目录当「学习库」：里面的每个子目录都算一张画布（带 notes/ 或 questions/ 的会被自动认出来）。如果这个目录自己就是一张画布（有 notes/ 或 questions/），那就只把它这一张加进画布列表，磁盘上什么都不写。',
		libScan: '扫描',

		libUp: '上一层',
		libHome: '主目录',
		libDesktop: '桌面',
		libNoSub: '这个目录下没有子目录',
		libIsCanvas: '画布',
		libNotCanvas: '普通目录',
		libPickHint: '点右边的「选择…」弹目录选择窗体；也可以直接把绝对路径粘进来，按 Enter 直接导入。',
		libImportedCanvas: '已把 {n} 加进画布列表',
		libScanning: '正在读取…',
		libExistsYes: '已存在',
		libExistsNo: '不存在（导入时会建出来）',
		libNotDir: '这不是一个目录',
		libTemplates: '.templates',
		libTemplatesYes: '已有，直接共用',
		libTemplatesNo: '还没有，导入时自动创建',
		libCanvasCount: '识别到的画布',
		libCanvasNone: '暂时没有（子目录里要有 notes/ 或 questions/）',
		libOtherDirs: '其他子目录',
		libNone: '无',
		libTruncated: '（子目录太多，只列了前 200 个）',
		libImportGo: '导入',
		libImported: '已导入 {n} 个画布',
		libImportedNone: '目录已就绪，但没识别到画布',
		libUnit: '个',
		libNeedAbs: '请填一个绝对路径，例如 /Users/你/Desktop/RootNotes',
		dirTemplatesShared: '共用',
			mapRefresh: '刷新导图',
		mindRoot: '学习画布',
		mmFold: '折叠',
		mmUnfold: '展开',
		del: '删除',
		delConfirm: '确认删除？',
		delFile: '删除本文件',
		delSection: '删除小节',
		delChapter: '删除整章',
		delPoint: '删除知识点',
		delQuestion: '删除此题',
		editQuestion: '编辑此题',
		qNew: '新建题目',
		qEdit: '编辑题目',
		kindChoice: '选择题',
		kindCase: '案例题',
		stemLabel: '题干',
		optionsLabel: '选项',
		optionHint: '点左侧圆点设为正确答案；留空的选项保存时会丢掉',
		explanationLabel: '解析',
		answerTextLabel: '答案与解析',
		answerTextHint: '直接写 markdown；多问案例题就按「问题 1 / 答案 / 问题 2 / 答案」往下写',
		addOption: '＋ 加选项',
		dropOption: '删除',
		saveAndNext: '保存并继续添加',
		errStem: '题干不能为空',
		errOptions: '选择题至少要两个有内容的选项',
		errAnswer: '请点圆点选择正确答案',
		errAnswerText: '案例题要填答案',
		savedNext: '已保存，可以继续添加下一题',
		pointEdit: '编辑知识点',
		pointTitleLabel: '标题',
		pointTagsLabel: '标签',
		pointTagsHint: '用逗号分隔，留空就清掉',
		pointBodyLabel: '内容',
		pointBodyHint: '支持 markdown：段落 / 列表 / 表格 / 引用 / 代码块，以及 $公式$ 和 ```mermaid 流程图',
		previewLabel: '实时预览',
		previewEmpty: '这里会实时显示渲染结果（公式、流程图都会渲染）',
		modeMd: 'Markdown',
		modeSrc: '源码',
		mdLoading: '编辑器加载中……',
		mdPlaceholder: '正文写这里……输入 / 可插入公式、表格、代码块；选中文字会弹出格式工具栏',
		mdFrontKept: 'YAML 头会原样保留（要改就在源码模式里改）',
		pointBodyPlaceholder: '一句话结论 + 关键要点……',
		errPointTitle: '标题不能为空',
		pointSaved: '已保存知识点',
		loadFailed: '读取失败',
		pointChanged: '这个知识点和文件对不上了（可能刚被改过），刷新页面再试一次',
		pointMissing: '没找到这个知识点',
		deleted: '已删除',
		cascade: '连带删除关联文件',
		/* Git 提交 */
		gitCommit: 'Git 提交',
		gitTitle: 'Git 提交',
		gitBranch: '分支',
		gitUpstream: '上游',
		gitSynced: '与远程一致',
		gitAhead: '领先',
		gitBehind: '落后',
		gitLastCommit: '上次提交',
		gitClean: '笔记里没有未提交的改动',
		gitGroupPlugin: '插件代码',
		gitGroupNotes: '笔记与题目',
		gitGroupOther: '其它',
		gitTruncated: '只显示前 400 个改动',
		gitStateNew: '新增',
		gitStateMod: '修改',
		gitStateDel: '删除',
		gitStateRen: '重命名',
		gitStateConflict: '冲突',
		mdBold: '加粗',
		mdItalic: '斜体',
		mdMath: '行内公式',
		mdMathBlock: '块级公式',
		mdTable: '表格',
		mdFlow: '流程图',
		mdList: '列表',
		mdQuote: '引用',
		mdLink: '链接',
		mdCode: '代码',
		mdTemplates: '模板',
		mdFormula: '公式',
		mdTemplateEmpty: '还没读到模板，检查模板文件',
		mdLoadFailed: '模板读取失败',
		mdReloadTemplates: '重新读取',
		mdCreateTemplates: '建模板文件',
		mdEditTemplates: '编辑模板文件',
		gitAiGenerate: '✦ AI 生成',
		gitAiBusy: '生成中…',
		gitAiCandidates: 'AI 候选（点一条填入）',
		gitAiFailed: 'AI 生成失败',
		gitScopeNotesHint: '只提交 notes/ 与 questions/ 里的内容',
		gitScopeLibHint: '整个学习库一起提交: 所有画布与其它改动都在这一次里',
		gitScopeOtherHint: '插件代码与其它改动不在这里提交',
		gitScope: '提交范围',
		gitScopeAll: '全部',
		gitScopePlugin: '只插件代码',
		gitScopeNotes: '只笔记文件',
		gitMessage: '提交信息',
		gitMessagePlaceholder: '例如：更新第 1 章笔记与知识点',
		gitCommitOnly: '仅提交',
		gitCommitPush: '提交并推送',
		gitPushOnly: '仅推送',
	gitPull: '拉取',
	gitPulling: '拉取中…',
	gitPulled: '已拉取远程更新',
	gitUpToDate: '本地已经是最新的',
	gitMergedFirst: '提交时已先合并远程更新',
	gitPullHint: '把远程更新拉下来合并到本地(不改写本地历史)',
	gitNoRemote: '没有配置远程, 没法拉取',
	gitConflictFiles: '有 {n} 个冲突文件没解决',
	gitPullConflictHint: '有冲突文件没解决, 先处理冲突',
		gitPushOnlyHint: '把已提交、还没推到远程的改动推上去',
		gitNoPush: '当前没有需要推送的提交',
		gitNothingToCommitYet: '没有新的改动可提交',
		gitCommitting: '提交中…',
		gitPushing: '推送中…',
		gitRefresh: '刷新',
		gitCommitted: '已提交',
		gitPushed: '已推送到远程',
		gitNoRepo: '这个目录不是 git 仓库',
		gitLoadFailed: '读取 git 状态失败',
		gitMsgBoth: '更新插件代码与笔记',
		gitMsgPlugin: '更新插件代码',
		gitMsgNotes: '更新笔记',
		gitMsgOther: '更新仓库内容',
		gitMsgLibrary: '更新学习库: 全部改动一次提交',
		gitHint: '只暂存所选范围里的改动, 推送发往 origin',
		gitEmptyMessage: '先写一句提交信息',
		deleteHint: '',
	};

	const en = {
		panel: 'Architect Notes',
		title: 'System Architect · Study Canvas',
		subtitle: 'folder = chapter · file = section · knowledge points + questions',
		search: 'Search knowledge points, sections, tags…',
		all: 'All',
		note: 'Notes',
		question: 'Questions',
		refresh: 'Rescan',
		chapters: 'Chapters',
		sections: 'Sections',
		points: 'Points',
		examples: 'Questions',
		words: 'chars',
		empty: 'No notes yet. Use “New chapter” or drop markdown into the workspace.',
		emptyChapter: 'No sections in this chapter',
		noMatch: 'Nothing matched',
		back: 'Back',
		backToMap: 'Chapter map',
		close: 'Close',
		edit: 'Edit',
		openSection: 'Open',
		editSection: 'Edit section',
		editPoint: 'Edit knowledge point',
		editQuestionFile: 'Edit questions',
		renameChapter: 'Rename chapter',
		rename: 'Rename',
		newSection: 'New section',
		newPoint: 'New point',
		addQuestion: '+ Add question',
		noQuestionYet: 'No question for this point yet — use the buttons on the right.',
		questionFile: 'Question file',
		insertQuestion: 'Insert question',
		ownFile: 'Own file',
		newChapter: 'New chapter',
		save: 'Save',
		saving: 'Saving…',
		saved: 'Saved',
		cancel: 'Cancel',
		close: 'Close',
		title2: 'Title',
		kind: 'Kind',
		parent: 'Parent folder',
		create: 'Create',
		reveal: 'Answer hidden · click to reveal',
		revealAll: 'Reveal all answers',
		hideAll: 'Hide all answers',
		collapse: 'Hide answer',
		emptyBody: '(no prose in this section)',
		emptyPoints: 'No knowledge points detected: use “## Point: title” to split them.',
		loading: 'Loading…',
		zoomIn: 'Zoom in',
		zoomOut: 'Zoom out',
		fit: 'Reset',
		fontLabel: 'Font',
		fontSmaller: 'Smaller font',
		fontLarger: 'Larger font',
		fontHint: 'Font size: click to reset 100%',
		skinLabel: 'Colors',
		skinHint: 'Colors and theme (Material Design palette)',
		themeLabel: 'Theme',
		themeDark: 'Dark',
		themeLight: 'Light',
		themeAuto: 'Follow system',
		themeHint: 'Follow system: switch light / dark with the OS appearance setting, live',
		cardColors: 'Card colors',
		cardColorsHint: 'Give each chapter, section and point its own color',
		cardColorsOn: 'On',
		cardColorsOff: 'Off',
		skinTech: 'Tech Blue (default)',
		skinBlue: 'Material Blue',
		skinCyan: 'Material Cyan',
		skinTeal: 'Material Teal',
		skinGreen: 'Material Green',
		skinLime: 'Material Lime',
		skinAmber: 'Material Amber',
		skinOrange: 'Material Orange',
		skinDeepOrange: 'Material Deep Orange',
		skinRed: 'Material Red',
		skinPink: 'Material Pink',
		skinPurple: 'Material Purple',
		skinDeepPurple: 'Material Deep Purple',
		skinIndigo: 'Material Indigo',
		skinBlueGrey: 'Material Blue Grey',
		focus: 'Full screen',
		focusHint: 'Hide the sidebar and let the canvas fill the window (click again or press Esc to restore)',
		focusExit: 'Exit full screen',
		questions: 'Questions',
		subPoints: 'Sub-points',
		subTopics: 'Sub-topics',
		searchHits: 'Matching points',
		chars: 'chars',
		modeCanvas: 'Canvas',
		modeMap: 'Mind map',
		rootTitle: 'My canvases',
		rootSubtitle: 'One canvas = one notes root folder',
		rootCount: 'canvases',
		rootNew: 'New canvas',
		rootNewHint: 'Pick a folder as this canvas root (defaults under your imported library); notes/ and questions/ are created for you (templates live in the library root .templates/)',
		rootEnter: 'Open canvas',
		rootDefault: 'built-in',
		rootForget: 'Remove from list',
		rootForgetHint: 'Moves it into a .remove/ folder next to it, then drops it from this list',
		rootRemoved: 'Removed from the list (folder moved into .remove/)',
		rootCreated: 'Canvas created',
		rootScanning: 'Counting…',
		rootNeedPath: 'Give an absolute path, e.g. /Users/you/Desktop/notes',
		rootName: 'Canvas name',
		rootPathLabel: 'Root folder',
		rootPathHint: 'Absolute path; leave empty to build it under your imported library. Created if missing, with notes/ and questions/ (templates live in the library root .templates/)',
		rootCreate: 'Create',
		rootRename: 'Rename canvas',
		rootRenameHint: 'Renaming renames the folder on disk (folder name = canvas name); names must be unique in the same folder',
		rootNameTaken: 'A canvas with that name already exists — pick another name',
		rootNeedName: 'Name cannot be empty',
		rootRenamed: 'Folder renamed',
		rootAll: 'All canvases',
		rootAllHint: 'Back to all canvases',
		rootHint: 'Canvas list: click a card to open it, + to create one, or ⇪ to import an existing folder',
		rootHintUnder: 'new canvases go under',
		rootRescanned: 'Rescanned',
		rootGone: 'Removed {n} canvas(es) that no longer exist on disk',
		settings: 'Settings',
		settingsHint: 'Settings: canvas folder',
		defaultRoot: 'Canvas folder',
		defaultRootHint: 'Every new canvas is created in a subfolder here (e.g. /Users/you/Desktop/WorkNotes/algorithms). Point it outside the plugin folder to keep notes separate.',
		currentCanvas: 'Current canvas',
		settingsAll: 'Canvas list (not inside a canvas)',
		settingsPluginDefault: 'Default root in plugin config (cordis.patch.yml)',
		dirNotes: 'Notes dir',
		dirQuestions: 'Questions dir',
		dirTemplates: 'Templates dir',
		settingsSaveOnly: 'Save only',
		settingsSaveEnter: 'Save & new canvas',
		settingsSaved: 'Settings saved',
		settingsNeedAbs: 'Enter an absolute path, e.g. /Users/you/Desktop/notes',
		libImport: 'Import folder',
		libTitle: 'Import an existing folder',
		libLabel: 'Folder',
		libNoPicker: 'No folder chooser here — type an absolute path instead.',
		libPicking: 'Choosing…',
		libChoose: '📁 Choose…',
		libHint: 'Pick a folder to use as your library: every subfolder counts as a canvas (those with notes/ or questions/ are detected automatically). If the folder is itself a canvas, only that one is added to the list and nothing is written to disk.',
		libScan: 'Scan',

		libUp: 'Up',
		libHome: 'Home',
		libDesktop: 'Desktop',
		libNoSub: 'This folder has no subfolders',
		libIsCanvas: 'canvas',
		libNotCanvas: 'folder',
		libPickHint: 'Click “Choose…” to open the folder chooser, or paste an absolute path and press Enter to import.',
		libImportedCanvas: 'Added {n} to the canvas list',
		libScanning: 'Reading…',
		libExistsYes: 'exists',
		libExistsNo: 'missing (created on import)',
		libNotDir: 'not a directory',
		libTemplates: '.templates',
		libTemplatesYes: 'present — shared',
		libTemplatesNo: 'missing — created on import',
		libCanvasCount: 'Canvases found',
		libCanvasNone: 'none yet (subfolders need notes/ or questions/)',
		libOtherDirs: 'Other subfolders',
		libNone: 'none',
		libTruncated: '(too many subfolders, showing the first 200)',
		libImportGo: 'Import',
		libImported: 'Imported {n} canvas(es)',
		libImportedNone: 'Folder ready, but no canvas was found',
		libUnit: '',
		libNeedAbs: 'Enter an absolute path, e.g. /Users/you/Desktop/RootNotes',
		dirTemplatesShared: 'shared',
			mapRefresh: 'Refresh map',
		mindRoot: 'Study canvas',
		mmFold: 'Collapse',
		mmUnfold: 'Expand',
		del: 'Delete',
		delConfirm: 'Delete?',
		delFile: 'Delete file',
		delSection: 'Delete section',
		delChapter: 'Delete chapter',
		delPoint: 'Delete point',
		delQuestion: 'Delete question',
		editQuestion: 'Edit question',
		qNew: 'New question',
		qEdit: 'Edit question',
		kindChoice: 'Multiple choice',
		kindCase: 'Case question',
		stemLabel: 'Prompt',
		optionsLabel: 'Options',
		optionHint: 'Click the dot to mark the right answer; empty options are dropped on save',
		explanationLabel: 'Explanation',
		answerTextLabel: 'Answer',
		answerTextHint: 'Markdown. For a multi-part case, write 问题 1 / answer / 问题 2 / answer',
		addOption: '+ Add option',
		dropOption: 'Remove',
		saveAndNext: 'Save and add another',
		errStem: 'The prompt cannot be empty',
		errOptions: 'A multiple-choice question needs at least two filled options',
		errAnswer: 'Pick the correct answer',
		errAnswerText: 'A case question needs an answer',
		savedNext: 'Saved — you can add the next one',
		pointEdit: 'Edit point',
		pointTitleLabel: 'Title',
		pointTagsLabel: 'Tags',
		pointTagsHint: 'Comma separated; clear the field to remove them',
		pointBodyLabel: 'Content',
		pointBodyHint: 'Markdown works: paragraphs / lists / tables / quotes / code, plus $math$ and ```mermaid diagrams',
		previewLabel: 'Live preview',
		previewEmpty: 'The rendered result appears here (math and diagrams included)',
		modeMd: 'Markdown',
		modeSrc: 'Source',
		mdLoading: 'Loading editor…',
		mdPlaceholder: 'Write here… type / to insert math, tables, code blocks; select text for a toolbar',
		mdFrontKept: 'YAML header is preserved (edit it in source mode)',
		pointBodyPlaceholder: 'One-line takeaway + key points…',
		errPointTitle: 'The title cannot be empty',
		pointSaved: 'Knowledge point saved',
		loadFailed: 'Could not read',
		pointChanged: 'This point no longer matches the file (it changed), refresh and retry',
		pointMissing: 'Knowledge point not found',
		deleted: 'Deleted',
		cascade: 'related files removed',
		/* Git commit */
		gitCommit: 'Git commit',
		gitTitle: 'Git commit',
		gitBranch: 'Branch',
		gitUpstream: 'Upstream',
		gitSynced: 'up to date',
		gitAhead: 'ahead',
		gitBehind: 'behind',
		gitLastCommit: 'Last commit',
		gitClean: 'No uncommitted changes in the notes',
		gitGroupPlugin: 'Plugin code',
		gitGroupNotes: 'Notes & questions',
		gitGroupOther: 'Other',
		gitTruncated: 'showing the first 400 changes only',
		gitStateNew: 'New',
		gitStateMod: 'Modified',
		gitStateDel: 'Deleted',
		gitStateRen: 'Renamed',
		gitStateConflict: 'Conflict',
		mdBold: 'Bold',
		mdItalic: 'Italic',
		mdMath: 'Inline formula',
		mdMathBlock: 'Block formula',
		mdTable: 'Table',
		mdFlow: 'Flowchart',
		mdList: 'List',
		mdQuote: 'Quote',
		mdLink: 'Link',
		mdCode: 'Code',
		mdTemplates: 'Templates',
		mdFormula: 'Formula',
		mdTemplateEmpty: 'No templates yet — check the template file',
		mdLoadFailed: 'Failed to load templates',
		mdReloadTemplates: 'Reload',
		mdCreateTemplates: 'Create template file',
		mdEditTemplates: 'Edit template file',
		gitAiGenerate: '✦ AI generate',
		gitAiBusy: 'Generating…',
		gitAiCandidates: 'AI candidates (click one to use)',
		gitAiFailed: 'AI generation failed',
		gitScopeNotesHint: 'commits only what is inside notes/ and questions/',
		gitScopeLibHint: 'commits the whole library in one go',
		gitScopeOtherHint: 'plugin code and other changes are not committed here',
		gitScope: 'Scope',
		gitScopeAll: 'Everything',
		gitScopePlugin: 'Plugin only',
		gitScopeNotes: 'Notes only',
		gitMessage: 'Commit message',
		gitMessagePlaceholder: 'e.g. update chapter 1 notes and key points',
		gitCommitOnly: 'Commit',
		gitCommitPush: 'Commit & push',
		gitPushOnly: 'Push',
	gitPull: 'Pull',
	gitPulling: 'Pulling…',
	gitPulled: 'pulled remote updates',
	gitUpToDate: 'already up to date',
	gitMergedFirst: 'merged remote updates first',
	gitPullHint: 'fetch and merge remote updates (never rebases)',
	gitNoRemote: 'no remote configured',
	gitConflictFiles: '{n} conflicted file(s) to resolve',
	gitPullConflictHint: 'resolve the conflicts first',
		gitPushOnlyHint: 'push commits that are not on the remote yet',
		gitNoPush: 'nothing to push right now',
		gitNothingToCommitYet: 'nothing new to commit',
		gitCommitting: 'Committing…',
		gitPushing: 'Pushing…',
		gitRefresh: 'Refresh',
		gitCommitted: 'Committed',
		gitPushed: 'pushed to origin',
		gitNoRepo: 'This directory is not a git repository',
		gitLoadFailed: 'Could not read git status',
		gitMsgBoth: 'update plugin code and notes',
		gitMsgPlugin: 'update plugin code',
		gitMsgNotes: 'update notes',
		gitMsgOther: 'update repository content',
		gitMsgLibrary: 'update the whole library at once',
		gitHint: 'stages only the selected scope; push goes to origin',
		gitEmptyMessage: 'Write a commit message first',
		deleteHint: '',
	};

		return { zh, en };
}
